### ISSUE TITLE
Action to release pro license

### ISSUE THREAD

**Issue by Dyhr** [game-ci/unity-activate#4]
I have just tested that the action works for my pro license, but there is the issue that you only have a limited number of activations.

We need an action to release the license after the build has completed, or if it fails.

**Comment by webbertakken** [comment]
Thanks for the feedback. I'll get right on it when I get back.

**Comment by webbertakken** [comment]
Progress can be tracked in the issue of the collections repository here: https://github.com/webbertakken/unity-actions/issues/17
