### ISSUE TITLE
Question: how is it that activation skips open project attempt?

### ISSUE THREAD

**Issue by nussetorten** [game-ci/unity-activate#56]
Love game.ci, love the unity-* suite of GitHub Actions, question re professional license activation:

When reproducing the license activation commands in my own environment (both unityci image and native editor), post-activation, Unity attempts to open the current working directory or the last opened project.  How does this action avoid this behavior?

Log from action (technically the /step/activate.sh from test-runner, but functionally equiv):
```
...
LICENSE SYSTEM [2021121 20:7:56] License activated successfully with user: *** 
LICENSE SYSTEM [2021121 20:7:56] Next license update check is after 2021-01-23T01:07:55
No valid Unity Editor license found. Please activate your license.
Activation complete.
```

Log from native editor:
```
LICENSE SYSTEM [2021127 14:23:10] License activated successfully with user: *** 
LICENSE SYSTEM [2021127 14:23:10] Next license update check is after 2021-01-28T14:23:10
[Package Manager] Server::Start -- Port 57536 was selected
 COMMAND LINE ARGUMENTS:
/opt/unity/Editor/Unity
-batchmode
-nographics
-logFile
/dev/stdout
-quit
-serial
(hidden)
-username
(hidden)
-password
(hidden)
[REDACTED: CURRENT WORK DIRECTORY]
[REDACTED: PROCEEDS TO IMPORT PROJECT, THEN QUIT...]
```

Observed with Unity 2019.4.4f1 and unityci/editor:ubuntu-2019.4.4f1-base-0.8.0

**Comment by webbertakken** [comment]
It's based on the combination of those specific command line arguments. Adding or removing one may undo this behaviour.

Also i'm not completely sure if we managed to reproduce this behaviour in unity-builder and unity-test-runner which include the activate step.

**Comment by nussetorten** [comment]
Perhaps just further proof that "[activation is kind of a mess](https://gitlab.com/gableroux/unity3d-gitlab-ci-example/-/issues/117#note_439595216)".  In any case, thanks for the (extremely!) speedy response!

**Comment by webbertakken** [comment]
Assuming this answered your question I will close it. Please feel free to provide any additional information for other people that find this issue, or to reopen the issue if it did not answer your question fully.
